### ISSUE TITLE
파일 읽기 오류 1 (data in src)

### ISSUE THREAD

**Issue by BlueBarrypi** [LeeSH825/y-24-1-capstone#1]
![fopen](https://github.com/LeeSH825/y-24-1-capstone/assets/145245566/8743f600-08ec-4d18-97c3-58eb189be8f3)

처음에 src 파일 안에 tr.csv (encoding된 mnsit training파일)을 포함시킴.
하지만 fopen 함수가 작동하지 않고 관련 서칭을 더해보니 SD card를 사용해야 한다는 글을 읽어 SD card에 옮겨서 다른 방법으로 실행함

**Comment by LeeSH825** [comment]
Test2

**Comment by sangwoo8392** [comment]
어쩌라고
